import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import moment from 'moment';
import Header from '@/components/cores/header';
import Footer from '@/components/cores/footer';
import { Provider } from 'react-redux';
import { store } from './store'

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Web Vu',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" style={{ backgroundColor: 'white' }}>
            <body className={inter.className}>
                <Provider store={store}>
                    <Header />
                    {children}
                    <Footer />
                </Provider>
            </body>
        </html>
    );
}
