
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import moment from 'moment'
import Header from './header/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{ backgroundColor: 'white' }}>
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html >
  )
}
